State
{
	StateName = "INIT",
	OnFigureRespawnEvent
	{
		WaitTime = 4,
		X = 520,
		Y = 387,
		Conditions =
		{
		},
		Actions =
		{
			FigureWalk{Tag="ClanDefender1", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender2", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender3", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender4", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender5", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender6", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender7", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender8", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender9", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender10", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender11", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender12", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender13", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender14", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender15", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender16", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender17", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender18", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender19", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender20", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender21", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender22", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender23", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender24", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender25", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender26", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender27", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender28", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender29", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender30", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender31", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender32", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender33", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender34", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender35", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender36", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender37", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender38", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender39", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender40", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender41", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender42", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender43", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender44", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender45", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender46", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender47", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender48", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender49", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender50", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender51", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender52", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender53", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender54", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender55", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender56", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender57", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender58", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender59", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender60", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender61", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender62", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender63", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender64", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender65", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender66", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender67", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender68", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender69", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender70", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender71", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender72", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender73", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="ClanDefender74", X = GetEntityX(), Y = GetEntityY()},
		},
	},
}
