State
{
	StateName = "INIT",
	OnFigureRespawnEvent
	{
		WaitTime = 6,
		X = 190,
		Y = 631,
		Conditions =
		{
		},
		Actions =
		{
			FigureWalk{Tag="PactDefender1", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender2", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender3", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender4", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender5", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender6", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender7", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender8", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender9", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender10", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender11", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender12", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender13", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender14", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender15", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender16", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender17", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender18", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender19", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender20", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender21", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender22", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender23", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender24", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender25", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender26", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender27", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender28", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender29", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender30", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender31", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender32", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender33", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender34", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender35", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender36", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender37", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender38", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender39", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender40", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender41", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender42", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender43", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender44", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender45", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender46", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender47", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender48", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender49", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender50", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender51", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender52", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender53", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender54", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender55", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender56", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender57", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender58", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender59", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender60", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender61", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender62", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender63", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender64", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender65", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender66", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender67", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender68", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender69", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender70", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender71", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender72", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender73", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender74", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender75", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender76", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender77", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender78", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender79", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender80", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender81", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender82", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender83", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender84", X = GetEntityX(), Y = GetEntityY()},
			FigureWalk{Tag="PactDefender85", X = GetEntityX(), Y = GetEntityY()},
		},
	},
}
